# frozen_string_literal: true

# a class for providing options for disqo quotas
# rubocop:disable Metrics/ModuleLength
module DisqoQuotaSelectionsHashes
  GENDER_OPTIONS = {
    '1': 'female',
    '2': 'male'
  }.freeze

  GEOCOUNTRY_OPTIONS = {
    US: 'United States',
    CA: 'Canada',
    AU: 'Australia'
  }.freeze

  GEOUSREGION_OPTIONS = {
    '1': 'Northeast',
    '2': 'Midwest',
    '3': 'South',
    '4': 'West'
  }.freeze

  GEO_US_REGION_OPTIONS = {
    AL: 'Alabama',
    AK: 'Alaska',
    AZ: 'Arizona',
    AR: 'Arkansas',
    CA: 'California',
    CO: 'Colorado',
    CT: 'Connecticut',
    DE: 'Delaware',
    FL: 'Florida',
    GA: 'Georgia',
    HI: 'Hawaii',
    ID: 'Idaho',
    IL: 'Illinois',
    IN: 'Indiana',
    IA: 'Iowa',
    KS: 'Kansas',
    KY: 'Kentucky',
    LA: 'Louisiana',
    ME: 'Maine',
    MD: 'Maryland',
    MA: 'Massachusetts',
    MI: 'Michigan',
    MN: 'Minnesota',
    MS: 'Mississippi',
    MO: 'Missouri',
    MT: 'Montana',
    NE: 'Nebraska',
    NV: 'Nevada',
    NH: 'New Hampshire',
    NJ: 'New Jersey',
    NM: 'New Mexico',
    NY: 'New York',
    NC: 'North Carolina',
    ND: 'North Dakota',
    OH: 'Ohio',
    OK: 'Oklahoma',
    OR: 'Oregon',
    PA: 'Pennsylvania',
    RI: 'Rhode Island',
    SC: 'South Carolina',
    SD: 'South Dakota',
    TN: 'Tennessee',
    TX: 'Texas',
    UT: 'Utah',
    VT: 'Vermont',
    VA: 'Virginia',
    WA: 'Washington',
    WV: 'West Virginia',
    WI: 'Wisconsin',
    WY: 'Wyoming',
    AA: 'U.S. Armed Forces – Americas',
    AE: 'U.S. Armed Forces – Europe',
    AP: 'U.S. Armed Forces – Pacific',
    AS: 'American Samoa',
    DC: 'District of Columbia',
    FM: 'Federated States of Micronesia',
    GU: 'Guam',
    MH: 'Marshall Islands',
    MP: 'Northern Mariana Islands',
    PR: 'Puerto Rico',
    PW: 'Palau',
    VI: 'Virgin Islands'
  }.freeze

  GEO_CANADA_REGION_OPTIONS = {
    AB: 'Alberta',
    BC: 'British Columbia',
    MB: 'Manitoba',
    NB: 'New Brunswich',
    NL: 'Newfoundland',
    NS: 'Nova Scotia',
    NU: 'Nunavut',
    NT: 'Northwest Territories',
    ON: 'Ontario',
    QC: 'Quebec',
    PE: 'P.E.I',
    SK: 'Saskatchewan',
    YT: 'Yukon'
  }.freeze

  GEO_AUSTRALIA_REGION_OPTIONS = {
    AU: 'Australia',
    ACT: 'Australian Capital Territory',
    CHR: 'Christmas Island',
    COC: 'Cocos (Keeling) Islands',
    HMD: 'Heard Island and McDonald Islands',
    NSW: 'New South Wales',
    NF: 'Norfolk Island',
    NT: 'Northern Territory',
    QLD: 'Queensland',
    SA: 'South Australia',
    TAS: 'Tasmania',
    VIC: 'Victoria',
    WA: 'Western Australia'
  }.freeze

  GEOREGION_OPTIONS = GEO_US_REGION_OPTIONS.merge(GEO_CANADA_REGION_OPTIONS).merge(GEO_AUSTRALIA_REGION_OPTIONS)

  RENT_OR_OWN_OPTIONS = {
    '3': 'Live With Parents / Relatives',
    '5': 'Own - Home',
    '6': 'Own - Apartment / Condo',
    '7': 'Rent - Home',
    '8': 'Rent - Apartment / Condo',
    '9': 'University Residence',
    '10': 'Farm',
    '4': 'Other'
  }.freeze

  ETHNICITY_OPTIONS = {
    '1': 'White / Caucasian',
    '2': 'Black / African American',
    '3': 'American Indian / Alaskan Native',
    '4': 'Asian',
    '9': 'Asian, Indian',
    '10': 'Asian, Chinese',
    '11': 'Asian, Filipino',
    '12': 'Asian, Japanese',
    '13': 'Asian, Korean',
    '14': 'Asian, Vietnamese',
    '15': 'Asian, Other',
    '5': 'Middle Eastern',
    '6': 'Pacific Islander',
    '16': 'Pacific Islander, Native Hawaiian',
    '17': 'Pacific Islander, Guamanian',
    '18': 'Pacific Islander, Samoan',
    '19': 'Pacific Islander, Other',
    '7': 'Hispanic or Mixed / Other Race',
    '8': 'Prefer Not to Say'
  }.freeze

  EDUCATION_LEVEL_OPTIONS = {
    '11': '3rd Grade or Less',
    '12': 'Middle School - Grades 4 - 8',
    '1': 'Completed Some High School',
    '2': 'High School Graduate',
    '9': 'Vocational Training / Trade School',
    '3': 'Some College / University',
    '4': 'Associate\'s / 2-Yr. Degree',
    '5': 'Bachelor\'s Degree',
    '6': 'Some Postgraduate Study',
    '7': 'Master\'s Degree',
    '8': 'Doctorate / PhD'
  }.freeze

  EMPLOYEMENT_STATUS_OPTIONS = {
    '1': 'Employed Full-Time',
    '2': 'Employed Part-Time',
    '3': 'Self-Employed Full-Time',
    '4': 'Self-Employed Part-Time',
    '5': 'Homemaker / Stay-at-Home Parent',
    '8': 'Student Full-Time',
    '9': 'Student Part-Time',
    '12': 'Active military',
    '13': 'Inactive military/Veteran',
    '6': 'Retired',
    '10': 'Permanently Unemployed / Disabled',
    '11': 'Unemployed',
    '14': 'None of the Above'
  }.freeze

  HOUSEHOLD_INCOME_OPTIONS = {
    '23': 'Less than $5,000',
    '24': '$5,000 to $9,999',
    '2': '$10,000 to $14,999',
    '3': '$15,000 to $19,999',
    '4': '$20,000 to $24,999',
    '5': '$25,000 to $29,999',
    '6': '$30,000 to $34,999',
    '7': '$35,000 to $39,999',
    '8': '$40,000 to $44,999',
    '9': '$45,000 to $49,999',
    '10': '$50,000 to $54,999',
    '11': '$55,000 to $59,999',
    '12': '$60,000 to $64,999',
    '13': '$65,000 to $69,999',
    '14': '$70,000 to $74,999',
    '15': '$75,000 to $79,999',
    '25': '$80,000 to $84,999',
    '26': '$85,000 to $89,999',
    '27': '$90,000 to $94,999',
    '28': '$95,000 to $99,999',
    '18': '$100,000 to $124,999',
    '19': '$125,000 to $149,999',
    '29': '$150,000 to $174,999',
    '30': '$175,000 to $199,999',
    '31': '200,000 to $249,999',
    '32': '$250,000 and above',
    '22': 'Prefer Not to Say'
  }.freeze

  JOB_POSITION_OPTIONS = {
    '32': 'C-Level (e.g. CEO, CFO), Owner, Partner, President',
    '33': 'Vice President (EVP, SVP, AVP, VP)',
    '34': 'Director (Group Director, Sr. Director, Director)',
    '35': 'Manager (Group Manager, Sr. Manager, Manager, Program Manager)',
    '36': 'Supervisor',
    '37': 'Administrative (Clerical or Support Staff)',
    '38': 'Associate / Senior Associate',
    '39': 'Consultant',
    '40': 'Analyst',
    '41': 'Professional / Professional Specialist',
    '42': 'Technician / Technical Specialist',
    '43': 'Tradesman / Trade Specialist',
    '44': 'Intern',
    '45': 'Volunteer',
    '31': 'None of the above'
  }.freeze

  ONLINE_PAYMENT_METHOD_OPTIONS = {
    '1': 'Online Banking',
    '2': 'Mobile Banking',
    '3': 'In-Store Payment With Mobile Phone',
    '4': 'Online Purchases With Mobile Phone',
    '5': 'PayPal',
    '6': 'BillMeLater',
    '7': 'Google Wallet',
    '8': 'Dwolla',
    '9': 'None of the Above'
  }.freeze

  OWN_LEASE_OPTIONS = {
    '1': 'Own',
    '2': 'Lease',
    '3': 'Don\'t Have a Car'
  }.freeze

  NEW_OLD_VEHICLE_OPTIONS = {
    '1': 'New Purchase',
    '2': 'New Lease',
    '3': 'Secondhand Purchase',
    '4': 'Secondhand Lease',
    '5': 'Don\'t Have a Car'
  }.freeze

  AUTO_PURCHASE_PROSPECT_OPTIONS = {
    '1': 'Yes',
    '2': 'No'
  }.freeze

  HIGH_TECH_DEVICES_OPTIONS = {
    '1': 'Android Smartphone',
    '2': 'iPhone',
    '3': 'Windows Smartphone',
    '4': 'Other Cell Phone (Not a Smartphone)',
    '5': 'Android Tablet',
    '6': 'iPad',
    '7': 'iPod',
    '8': 'Windows Surface Tablet',
    '9': 'Other Tablet',
    '10': ' HDTV (High-Definition Television)',
    '11': ' Home Theater System',
    '12': ' 3D Television',
    '13': ' Smart Television',
    '14': ' Gaming Device',
    '15': ' Digital Camcorder',
    '16': ' DVD Player',
    '17': ' Blue Ray Disc Player',
    '18': ' None of the Above'
  }.freeze

  EMPLOYER_TYPE_OPTIONS = {
    '1': 'A For-Profit Business',
    '2': 'A Non-Profit, Charitable or Religious Organization',
    '3': 'A Government Agency, Office, Entity or Institution',
    '4': 'I Am Not Employed'
  }.freeze

  YEARS_IN_INDUSTRY_OPTIONS = {
    '1': 'Less Than 1 Year',
    '2': '1 to 3 Years',
    '3': '4 to 6 Years',
    '4': '7 to 10 Years',
    '5': 'More Than 10 Years',
    '6': 'I Am Not Employed'
  }.freeze

  EMPLOYMENT_DEPARTMENT_OPTIONS = {
    '1': 'Accounting / Finance',
    '2': 'Administrative / Clerical',
    '3': 'Advertising / Marketing',
    '4': 'Agriculture (Farming / Ranching)',
    '5': 'Architecture / Interior Design',
    '6': 'Banking',
    '7': 'Biotech / R&D / Science',
    '8': 'Building Construction / Skilled Trades',
    '9': 'Business / Strategic Management',
    '10': 'Communications / PR',
    '11': 'Compliance / Risk Management',
    '12': 'Creative / Design',
    '13': 'Customer Support / Client Support',
    '14': 'Editorial / Writing',
    '15': 'Education / Training',
    '16': 'Engineering',
    '17': 'Food Services / Hospitality',
    '18': 'Human Resources',
    '19': 'Installation / Maintenance / Repair',
    '20': 'Insurance',
    '21': 'Information Technology',
    '22': 'Legal',
    '23': 'Logistics / Transportation',
    '24': 'Manufacturing / Production / Operations',
    '25': 'Medical / Health',
    '26': 'Product Management',
    '27': 'Project / Program Management',
    '28': 'Public Service (Military / Law Enforcement / Fire Services / Emergency Services)',
    '29': 'Purchasing / Procurement',
    '30': 'Quality Assurance / Safety',
    '31': 'Real Estate / Mortgage Professionals',
    '32': 'Sales / Retail / Business Development',
    '33': 'Security / Protective Services',
    '34': 'Other',
    '35': 'I Am Not Employed',
    '36': 'Technology Development Software',
    '37': 'Technology Development Hardware'
  }.freeze

  SMARTPHONE_USE_OPTIONS = {
    '1': '0 to 1',
    '2': '1 to 2',
    '3': '2 to 3',
    '4': '4 to 5',
    '5': '5+'
  }.freeze

  INTERNET_PERSONAL_USE_OPTIONS = {
    '1': 'Every Day or Almost Every Day',
    '2': 'Several Times a Week',
    '3': 'Once a Week',
    '4': 'Several Times a Month',
    '5': 'Several Times a Year',
    '6': 'Don\'t Use the Internet for Personal Purposes'
  }.freeze

  GROCERY_SHOPPING_DUTY_OPTIONS = {
    '1': 'All of It',
    '2': 'Almost All of It',
    '3': 'About Half of It',
    '4': 'Less Than Half',
    '5': 'None'
  }.freeze

  CHILDREN_OPTIONS = {
    '1': '0',
    '2': '1',
    '3': '2',
    '4': '3',
    '5': '4',
    '6': '5',
    '7': '6',
    '8': '7',
    '9': '8'
  }.freeze

  INDUSTRY_OPTIONS = {
    '67': 'Computer - Electronics',
    '68': 'Computer - Hardware',
    '69': 'Computer - Reseller (Software / Hardware)',
    '70': 'Computer - Security',
    '71': 'Computer - Software',
    '72': 'Computer - Storage',
    '61': 'Consumer - Electronics',
    '19': 'Consumer - Food & Beverages',
    '73': 'Consumer - Packaged Goods',
    '60': 'Financial - Accounting',
    '7': 'Financial - Banking',
    '74': 'Financial - Brokerage',
    '75': 'Information Technology',
    '25': 'Internet',
    '31': 'Market Research',
    '76': 'Technology Services - Computers',
    '77': 'Technology Services - Software',
    '78': 'Technology Services - Web Development',
    '79': 'Technology Services - Other',
    '80': 'Accommodation - Hotels',
    '81': 'Accommodation - Restaurants',
    '82': 'Advertising',
    '4': 'Architecture',
    '83': 'Aviation',
    '13': 'Construction',
    '17': 'Entertainment',
    '84': 'Equipment',
    '18': 'Fashion / Apparel',
    '30': 'Manufacturing',
    '85': 'Marketing',
    '86': 'Media',
    '40': 'Printing / Publishing',
    '87': 'Public Relations',
    '48': 'Sales',
    '88': 'Skills Trade - Carpentry',
    '15': 'Skills Trade - Electrical',
    '45': 'Skills Trade - Repair Services',
    '89': 'Tourism',
    '66': 'Transportation',
    '54': 'Travel',
    '90': 'Athletics - Fitness',
    '49': 'Athletics - Sports',
    '10': 'Casino',
    '12': 'Communications/Information',
    '14': 'Education',
    '91': 'Employment',
    '92': 'Environmental Services',
    '62': 'Human Resources',
    '24': 'Insurance',
    '26': 'Law - Enforcement',
    '27': 'Law - Legal Services',
    '93': 'Non Profit / Charity',
    '38': 'Personal Services',
    '41': 'Public Administration',
    '94': 'Public Sector',
    '43': 'Real Estate / Property',
    '46': 'Retail / Wholesale Trade',
    '44': 'Religious Organizations',
    '95': 'Social Services',
    '65': 'Telecommunications',
    '96': 'Aerospace / Defense',
    '6': 'Automotive',
    '97': 'Bio-Tech',
    '2': 'Business Services - Administrative Support',
    '9': 'Business Services - Other',
    '98': 'Consulting - Training',
    '29': 'Consulting - Other',
    '16': 'Engineering',
    '20': 'Government',
    '99': 'Health Care - Dentistry',
    '100': 'Health Care - Pharmaceuticals',
    '101': 'Health Care - Veterinary Services',
    '102': 'Health Care - Other',
    '103': 'Industrial Goods',
    '104': 'Logistics - Distribution',
    '105': 'Logistics - Shipping',
    '106': 'Logistics - Warehousing',
    '32': 'Military',
    '64': 'Security',
    '107': 'Agriculture - Fishing',
    '108': 'Agriculture - Forestry',
    '109': 'Agriculture - Hunting',
    '110': 'Agriculture - Other',
    '11': 'Chemical Industry',
    '111': 'Energy - Oil & Gas',
    '112': 'Energy - Other',
    '28': 'Leisure & Recreation Services',
    '113': 'Materials - Chemical',
    '114': 'Materials - Metal',
    '115': 'Materials - Mineral',
    '116': 'Materials - Oil',
    '117': 'Materials - Plastics',
    '118': 'Materials - Rubber',
    '119': 'Mining - Metals',
    '120': 'Mining - Minerals',
    '121': 'Mining - Oils',
    '122': 'Natural Resources',
    '55': 'Utilities & Energy Providers - gas, water, electricity',
    '123': 'Waste Management',
    '58': 'None of the Above',
    '124': "I Don't Work"
  }.freeze

  PURCHASE_AUTH_OPTIONS = {
    '2': 'Advertising / Marketing Services',
    '3': 'Company Liability / Insurance',
    '4': 'IT Hardware',
    '5': 'IT Software',
    '6': 'Consulting Services',
    '7': 'Employee Benefits',
    '8': 'Financial Services',
    '9': 'Food / Beverage Services',
    '10': 'HR / Personnel Services',
    '11': 'Internet / Data Services',
    '12': 'Legal Services',
    '13': 'Facilities / Maintenance Services',
    '14': 'Market Research',
    '15': 'Meeting Accommodations',
    '17': 'Office Services / Moving',
    '18': 'Office Supplies / Equipment',
    '19': 'Print / Copy / Photo Services',
    '20': 'Utilities',
    '21': 'Vehicles / Automobile Services',
    '22': 'Raw Materials / Components',
    '23': 'Real Estate Services',
    '24': 'Sales / Business Development',
    '25': 'Security Services',
    '26': 'Shipping / Mail Services',
    '27': 'Strategic Company Goals',
    '28': 'Telecommunications',
    '29': 'Training',
    '30': 'Travel / Transportation',
    '31': 'Other',
    '32': 'None of the Above'
  }.freeze

  FINANCIAL_DECISION_MAKER_OPTIONS = {
    '1': 'Yes',
    '2': 'No'
  }.freeze

  INVESTABLE_ASSETS_OPTIONS = {
    '1': 'Less than $50,000',
    '2': '$50,000 - $74,999',
    '3': '$75,000 - $99,999',
    '4': '$100,000 - $149,999',
    '5': '$150,000 - $199,999',
    '6': '$200,000 - $499,999',
    '7': '$500,000 - $999,999',
    '8': '$1,000,000 or more',
    '9': 'No investable assets',
    '10': 'Prefer not to say'
  }.freeze

  INSURANCE_TYPE_OPTIONS = {
    '1': 'Auto Insurance',
    '2': 'Home Insurance',
    '3': 'Renters Insurance',
    '4': 'Health Insurance'
  }.freeze

  LOAN_TYPE_OPTIONS = {
    '1': 'Auto Loan',
    '2': 'Student Loan',
    '3': 'Mortgage',
    '4': 'Credit Card Loan',
    '5': 'Personal Loans (Non Credit Card)',
    '6': 'None of the Above'
  }.freeze

  FINANCIAL_PRODUCT_OPTIONS = {
    '1': 'Checking Account',
    '2': 'Business Checking Account',
    '3': 'Savings Account',
    '4': 'Investment Products',
    '5': 'Investment Properties',
    '6': 'IRA or Roth IRA (Individual Retirement Account)',
    '7': 'Pension Offered By Employer',
    '8': 'Pension Not From Employer',
    '9': 'Retirement Plan (401k, 403b, 429, 457)',
    '10': 'None of the Above'
  }.freeze

  INTERNET_BUSINESS_USE_OPTIONS = {
    '1': 'Every Day or Almost Every Day',
    '2': 'Several Times a Week',
    '3': 'Once a Week',
    '4': 'Several Times a Month',
    '5': 'Several Times a Year',
    '6': "Don't Use the Internet for Business Purposes"
  }.freeze

  ONLINE_SHOPPING_OPTIONS = {
    '1': 'Yes, 1 to 2 Times',
    '2': 'Yes, 3 to 6 Times',
    '3': 'Yes, 7 to 12 Times',
    '4': 'Yes, More Than 12 Times',
    '5': 'No'
  }.freeze

  ONLINE_PURCHASE_OPTIONS = {
    '18': 'Airline Tickets',
    '1': 'Clothing or Shoes',
    '2': 'Books',
    '3': 'Dating Website Membership',
    '4': 'Electronics Equipment (TV, DVD player, etc.)',
    '19': 'Flowers',
    '5': 'Furniture',
    '6': 'Games',
    '7': 'Hardware',
    '8': 'Health and Beauty Products',
    '20': 'Hotel Reservation',
    '9': 'Household Appliances',
    '10': 'Medicine',
    '11': 'Music',
    '12': 'Secondhand Goods',
    '13': 'Software',
    '14': 'Sports Goods',
    '15': 'Event Tickets (Cinema, Theatre, Sports)',
    '16': 'Other',
    '17': 'I Have Not Purchased Anything'
  }.freeze

  SOCIAL_NETWORKS_OPTIONS = {
    '1': 'Facebook',
    '2': 'Twitter',
    '3': 'LinkedIn',
    '4': 'Pintrest',
    '5': 'Google Plus +',
    '6': 'Tumblr',
    '7': 'Instagram',
    '8': 'YouTube',
    '9': 'Flickr',
    '10': 'Vine',
    '11': 'Meetup',
    '12': 'Tagged',
    '13': 'Bebo',
    '14': 'ClassMates',
    '15': 'MySpace',
    '16': 'Other',
    '17': 'None'
  }.freeze

  SOCIAL_NETWORK_USE_OPTIONS = {
    '1': 'Every Day or Almost Every Day',
    '2': 'Several Times a Week',
    '3': 'Once a Week',
    '4': 'Several Times a Month',
    '5': 'Less Often',
    '6': 'Never'
  }.freeze

  FAVORITE_PUBLICATIONS_OPTIONS = {
    '16': 'Newspaper',
    '3': 'Arts & Crafts Magazines',
    '17': 'Automotive Magazines',
    '2': 'Computers & Electronics Magazines',
    '18': 'Cooking & Food Magazines',
    '19': 'Entertainment & TV Magazines',
    '4': 'Fashion, Style or Beauty Magazines',
    '20': 'Financial & Business Magazines',
    '21': 'Health, Fitness or Sports Magazines',
    '22': 'House & Gardening Magazines',
    '8': "Men's Magazines (GQ, Maxim, etc.)",
    '23': 'Music Magazines',
    '9': 'Parenting',
    '13': 'Politics',
    '14': 'Science, Nature or Medical Magazines',
    '24': 'Technology Magazines',
    '25': 'Teen Magazines',
    '26': 'Travel Magazines',
    '15': 'Other',
    '27': "Don't Read Publications"
  }.freeze

  STORE_TYPE_OPTIONS = {
    '1': 'Auto Supply and Auto Service',
    '2': 'Books and Media',
    '3': 'Computer and Home Electronics',
    '4': 'Convenience Stores (7Eleven, CircleK, QT, etc.)',
    '5': "Department Stores (Sears, Macy's)",
    '6': 'Discount Stores (Kmart, Target)',
    '7': 'Drug stores (Rite Aid, CVS)',
    '8': 'Hardware / Home Supply (Home Depot)',
    '9': 'Jewelry',
    '10': 'Office Supplies',
    '11': 'Online-Only Retailers',
    '12': 'Shopping Channel (HSN, QVC)',
    '13': 'Specialty Clothing',
    '14': 'Sporting Goods',
    '15': 'Supermarket or Grocery Stores (Kroger, Albertsons, Safeway, etc.)',
    '16': "Toys/Children's",
    '17': "Wholesale Clubs (Sam's Club, Costco, BJs, etc.)",
    '18': 'None of the Above'
  }.freeze

  PURCHASED_ITEMS_OPTIONS = {
    '1': 'Alcohol',
    '2': 'Gourmet Foods',
    '3': 'Organic Foods',
    '22': 'Vitamins / Supplements',
    '23': 'Medication',
    '4': 'Tobacco Products',
    '5': "Women's Clothing",
    '6': "Men's Clothing",
    '7': "Children's Clothing",
    '8': 'Big / Tall, Plus-Sized Clothing',
    '9': 'Kitchen & Major Appliances',
    '10': 'Furniture',
    '11': 'Outdoor Furniture',
    '12': 'Office Supplies',
    '13': 'Books',
    '14': 'CDs/DVDs',
    '15': 'Sporting Goods',
    '16': 'Luggage',
    '17': 'Bedding / Towels',
    '18': 'Wedding or Shower Gifts',
    '19': 'Gardening Equipment or Supplies',
    '20': 'Home Improvement or Hardware',
    '21': 'None of the Above'
  }.freeze

  GROCERY_PURCHASES_OPTIONS = {
    '1': 'Frozen Dinners',
    '2': 'Frozen Pizza',
    '3': 'Frozen Dough Products',
    '4': 'Juice / Orange Juice',
    '5': 'Carbonated Beverages',
    '6': 'Coffee',
    '7': 'Tea',
    '8': 'Yogurt',
    '9': 'Soy-Based Products',
    '10': 'Baby Food',
    '11': 'Packaged Baking Mixes',
    '12': 'Packaged Cookies/Snack Bars',
    '13': 'Snack Foods (Chips / Popcorn)',
    '14': 'Fruit Snacks',
    '15': 'Candy/Chocolate',
    '16': 'Cereal',
    '17': 'Health Foods',
    '18': 'Vitamins / Supplements',
    '19': 'Sugar-Free, Reduced-Calorie, Low-Carb Candy',
    '20': 'None of the Above'
  }.freeze

  PURCHASE_TYPE_OPTIONS = {
    '1': 'Clothing / Accessories',
    '2': 'Food',
    '3': 'Books / CDs / DVDs',
    '4': 'Electronics',
    '5': 'Appliances',
    '6': 'Furniture',
    '7': 'Office Supplies',
    '8': 'Other',
    '9': 'None'
  }.freeze

  RESTAURANT_VISITS_OPTIONS = {
    '1': 'Every Day or Almost Every Day',
    '2': 'Several Times a Week',
    '3': 'Once a Week',
    '4': 'Several Times a Month',
    '5': 'Less Often / Never'
  }.freeze

  FAST_FOOD_VISITS_OPTIONS = {
    '1': 'Every Day or Almost Every Day',
    '2': 'Several Times a Week',
    '3': 'Once a Week',
    '4': 'Several Times a Month',
    '5': 'Less Often / Never'
  }.freeze

  COOKING_FREQUENCY_OPTIONS = {
    '1': 'Every Day or Almost Every Day',
    '2': 'Several Times a Week',
    '3': 'Once a Week',
    '4': 'Several Times a Month',
    '5': 'Less Often / Never'
  }.freeze

  ALCOHOL_CONSUMPTION_OPTIONS = {
    '1': 'Yes',
    '2': 'No'
  }.freeze

  ALCOHOL_CONSUMPTION_TYPES_OPTIONS = {
    '1': 'Gin',
    '2': 'Vodka',
    '3': 'Rum',
    '4': 'Whiskey',
    '5': 'Tequila',
    '6': 'Brandy',
    '7': 'Champagne',
    '8': 'Red Wine',
    '9': 'White Wine',
    '10': 'Rose Wine',
    '11': 'Sparkling Wine',
    '12': 'Vermouth',
    '17': 'Domestic beer',
    '18': 'Imported Beer',
    '14': 'Cider',
    '15': 'Other',
    '16': 'I Have Not Drunk Alcohol'
  }.freeze

  WEEKLY_ALCOHOL_CONSUMPTION_OPTIONS = {
    '1': '0',
    '2': '1 to 4',
    '3': '5 to 10',
    '4': '11 to 14',
    '5': '15+'
  }.freeze

  HEALTH_OPTIONS = {
    '23': 'Food Allergies',
    '24': 'Hay Fever',
    '25': 'Lactose Intolerant',
    '26': 'Other Allergies',
    '27': 'Alcohol Abuse',
    '28': 'Drug Addiction',
    # '158': 'Opioid Dependence', duplicate keys
    '29': 'Smoking Addiction',
    '31': 'Celiac Disease',
    '32': 'Chronic Fatigue Syndrome',
    '34': 'Lupus',
    '35': 'Rheumatoid Arthritis',
    '36': 'Other Autoimmune Disorder',
    '37': 'Asthma',
    # '159': 'Chronic Cough', duplicate keys
    '38': 'Bronchitis',
    '39': 'COPD',
    '160': 'Cystic Fibrosis',
    '40': 'Emphysema',
    '41': 'Pneumonia',
    '42': 'Tuberculosis',
    '43': 'Other Breathing Condition',
    '161': 'Myeloma',
    '44': 'Breast Cancer',
    '45': 'CLL (Chronic Lymphocytic Leukemia)',
    '46': 'Colorectal Cancer',
    '47': 'Leukemia',
    '48': 'Lung Cancer',
    '49': 'Prostate Cancer',
    '50': 'Skin Cancer',
    '51': 'Oral Cancer',
    '52': 'Other Cancer',
    '53': 'Canker Sores',
    '54': 'Dental Cavities',
    '55': 'Gum Disease',
    '56': 'Other Oral Condition',
    '57': 'Colitis',
    '58': 'Constipation',
    '59': 'Crohn\'s Disease',
    '60': 'Diarrhea',
    '61': 'Gastro Esophageal Reflux (GERD)',
    '62': 'Gastroenteritis',
    '63': 'Hemorrhoids',
    '64': 'Irritable Bowel Syndrome',
    '65': 'Reflux',
    '66': 'Ulcerative Colitis',
    '67': 'Ulcers',
    '68': 'Other Digestive Condition',
    '69': 'Anorexia Nervosa',
    '70': 'Binge Eating Disorder',
    '71': 'Bulimia Nervosa',
    '72': 'Other Eating Disorder',
    '73': 'Astigmatism',
    '74': 'Farsightedness',
    '75': 'Nearsightedness',
    '76': 'Other Eye Condition',
    '77': 'Hearing Loss',
    '78': 'Ruptured Eardrum',
    '79': 'Other Ear Condition',
    '80': 'Nasal Polyps',
    '81': 'Sinusitis',
    '82': 'Other Nose/Sinus Condition',
    '83': 'Other Throat Condition',
    '84': 'Anemia',
    '85': 'Angina',
    '86': 'Arrhythmia/Atrial Fibrillation',
    '87': 'Cardiovascular Disease',
    '88': 'Diabetes Type 1',
    '89': 'Diabetes Type 2',
    '90': 'Hemophilia',
    '91': 'High Blood Pressure',
    '92': 'High Cholesterol',
    '93': 'Hypertension',
    '163': 'Acute Coronary Syndrome (ACS)',
    '94': 'Heart Failure',
    '95': 'Other Heart Condition',
    '96': 'Other Blood Condition',
    '97': 'Arthritis',
    '98': 'Back/Neck Pain',
    '99': 'Carpal Tunnel Syndrome',
    '100': 'Fibromyalgia',
    '101': 'Gout',
    '102': 'Joint Replacement',
    '103': 'Osteoarthritis',
    '104': 'Osteoporosis',
    '164': 'Axial Spondyloarthritis',
    '165': 'Ankylosing Spondylitis',
    '105': 'Other Joint / Muscle Condition',
    '106': 'Chronic Kidney Disease',
    '107': 'Kidney Failure',
    '108': 'Overactive Bladder',
    '109': 'Urinary Incontinence',
    '110': 'Urinary Tract Infections',
    '111': 'Other Kidney / Urinary Disorder',
    '112': 'Cirrhosis',
    '113': 'Hepatitis',
    '114': 'Other Liver Condition',
    '115': 'Men\'s Health - Erectile Dysfunction (ED)',
    '116': 'Men\'s Health - Hair Loss',
    '117': 'Men\'s Health - Infertility',
    '118': 'Men\'s Health - Premature Ejaculation',
    '119': 'Other Men\'s Health Issue',
    '120': 'Anxiety',
    '121': 'Bipolar Disorder',
    '122': 'Depression',
    '123': 'Other Mental / Behavioral Issue',
    '124': 'ADD/ADHD',
    '125': 'Alzheimer\'s Disease',
    '126': 'Autism',
    '127': 'Epilepsy',
    '128': 'Migraine',
    '129': 'Motor Neuron Disease',
    '130': 'Multiple Sclerosis',
    '131': 'Parkinson\'s Disease',
    '132': 'Schizophrenia',
    '133': 'Stroke',
    '134': 'Other Neurological Condition',
    '135': 'HIV - Aids',
    '136': 'Syphilis',
    '137': 'Other Sexual Health Issue',
    '139': 'Other Infectious Disease',
    '140': 'Acne',
    '141': 'Eczema',
    '142': 'Psoriasis',
    # '158': 'Psoriatic Arthritis', duplicate keys
    # '159': 'Rosacea', duplicate keys
    '143': 'Shingles',
    '144': 'Other Skin Condition',
    '145': 'Insomnia',
    '146': 'Restless Leg Syndrome',
    '147': 'Other Sleeping Disorder',
    '148': 'Hypothyroidism',
    '149': 'Other Thyroid Condition',
    '150': 'Obesity',
    '151': 'Other Weight Condition',
    '152': 'Women\'s Health - Endometriosis',
    '153': 'Women\'s Health - Infertility',
    '154': 'Women\'s Health - Menopause',
    '155': 'Other Women\'s Health Issue',
    '21': 'Prefer Not to Say',
    '157': 'No Illnesses / Conditions in Household'
  }.freeze

  PERSONAL_HEALTH_OPTIONS = {
    '23': 'Food Allergies',
    '24': 'Hay Fever',
    '25': 'Lactose Intolerant',
    '26': 'Other Allergies',
    '27': 'Alcohol Abuse',
    '28': 'Drug Addiction',
    '29': 'Smoking Addiction',
    '31': 'Celiac Disease',
    '32': 'Chronic Fatigue Syndrome',
    '34': 'Lupus',
    '35': 'Rheumatoid Arthritis',
    '36': 'Other Autoimmune Disorder',
    '37': 'Asthma',
    '38': 'Bronchitis',
    '39': 'COPD',
    '40': 'Emphysema',
    '41': 'Pneumonia',
    '42': 'Tuberculosis',
    '43': 'Other Breathing Condition',
    '44': 'Breast Cancer',
    '45': 'CLL (Chronic Lymphocytic Leukemia)',
    '46': 'Colorectal Cancer',
    '47': 'Leukemia',
    '48': 'Lung Cancer',
    '49': 'Prostate Cancer',
    '50': 'Skin Cancer',
    '51': 'Oral Cancer',
    '52': 'Other Cancer',
    '53': 'Canker Sores',
    '54': 'Dental Cavities',
    '55': 'Gum Disease',
    '56': 'Other Oral Condition',
    '57': 'Colitis',
    '58': 'Constipation',
    '59': 'Crohn\'s Disease',
    '60': 'Diarrhea',
    '61': 'Gastro Esophageal Reflux (GERD)',
    '62': 'Gastroenteritis',
    '63': 'Hemorrhoids',
    '64': 'Irritable Bowel Syndrome',
    '65': 'Reflux',
    '66': 'Ulcerative Colitis',
    '67': 'Ulcers',
    '68': 'Other Digestive Condition',
    '69': 'Anorexia Nervosa',
    '70': 'Binge Eating Disorder',
    '71': 'Bulimia Nervosa',
    '72': 'Other Eating Disorder',
    '73': 'Astigmatism',
    '74': 'Farsightedness',
    '75': 'Nearsightedness',
    '76': 'Other Eye Condition',
    '77': 'Hearing Loss',
    '78': 'Ruptured Eardrum',
    '79': 'Other Ear Condition',
    '80': 'Nasal Polyps',
    '81': 'Sinusitis',
    '82': 'Other Nose/Sinus Condition',
    '83': 'Other Throat Condition',
    '84': 'Anemia',
    '85': 'Angina',
    '86': 'Arrhythmia/Atrial Fibrillation',
    '87': 'Cardiovascular Disease',
    '88': 'Diabetes Type 1',
    '89': 'Diabetes Type 2',
    '90': 'Hemophilia',
    '91': 'High Blood Pressure',
    '92': 'High Cholesterol',
    '93': 'Hypertension',
    '94': 'Heart Failure',
    '95': 'Other Heart Condition',
    '96': 'Other Blood Condition',
    '97': 'Arthritis',
    '98': 'Back/Neck Pain',
    '99': 'Carpal Tunnel Syndrome',
    '100': 'Fibromyalgia',
    '101': 'Gout',
    '102': 'Joint Replacement',
    '103': 'Osteoarthritis',
    '104': 'Osteoporosis',
    '105': 'Other Joint / Muscle Condition',
    '106': 'Chronic Kidney Disease',
    '107': 'Kidney Failure',
    '108': 'Overactive Bladder',
    '109': 'Urinary Incontinence',
    '110': 'Urinary Tract Infections',
    '111': 'Other Kidney / Urinary Disorder',
    '112': 'Cirrhosis',
    '113': 'Hepatitis',
    '114': 'Other Liver Condition',
    '115': 'Men\'s Health - Erectile Dysfunction (ED)',
    '116': 'Men\'s Health - Hair Loss',
    '117': 'Men\'s Health - Infertility',
    '118': 'Men\'s Health - Premature Ejaculation',
    '119': 'Other Men\'s Health Issue',
    '120': 'Anxiety',
    '121': 'Bipolar Disorder',
    '122': 'Depression',
    '123': 'Other Mental / Behavioral Issue',
    '124': 'ADD/ADHD',
    '125': 'Alzheimer\'s Disease',
    '126': 'Autism',
    '127': 'Epilepsy',
    '128': 'Migraine',
    '129': 'Motor Neuron Disease',
    '130': 'Multiple Sclerosis',
    '131': 'Parkinson\'s Disease',
    '132': 'Schizophrenia',
    '133': 'Stroke',
    '134': 'Other Neurological Condition',
    '135': 'HIV - Aids',
    '136': 'Syphilis',
    '137': 'Other Sexual Health Issue',
    '139': 'Other Infectious Disease',
    '140': 'Acne',
    '141': 'Eczema',
    '142': 'Psoriasis',
    '143': 'Shingles',
    '144': 'Other Skin Condition',
    '145': 'Insomnia',
    '146': 'Restless Leg Syndrome',
    '147': 'Other Sleeping Disorder',
    '148': 'Hypothyroidism',
    '149': 'Other Thyroid Condition',
    '150': 'Obesity',
    '151': 'Other Weight Condition',
    '152': 'Women\'s Health - Endometriosis',
    '153': 'Women\'s Health - Infertility',
    '154': 'Women\'s Health - Menopause',
    '155': 'Other Women\'s Health Issue',
    '21': 'Prefer Not to Say',
    '157': 'No Illnesses / Conditions'
  }.freeze

  YEARLY_TRAVEL_FREQUENCY_OPTIONS = {
    '2': '3 to 4 Times',
    '1': '1 to 2 Times',
    '3': '5 to 10 Times',
    '4': 'More Than 10 Times',
    '5': 'None of the Above'
  }.freeze

  TRAVEL_SITE_OPTIONS = {
    '1': 'Airline Company Websites (American Airlines, Lufthansa, etc.)',
    '2': 'Car Rental Websites (Hertz, Avis, etc.)',
    '3': 'Travel Agency Websites (Expedia, Orbitz, Etc.)',
    '4': 'Hotel Websites (Hotels.com, Booking.com, etc.)',
    '5': 'Price Comparison Websites (Farecompare.com, Kayak.com, etc.)',
    '6': 'Other Websites',
    '7': 'I Haven\'t Used Any Website'
  }.freeze

  EMPLOYEE_COUNT_OPTIONS = {
    '1': '1-10',
    '2': '11-50',
    '3': '51-100',
    '4': '101-500',
    '5': '501-1000',
    '6': '1001-5000',
    '7': 'Greater than 5000',
    '8': "I Don't Work"
  }.freeze

  VEHICLE_OWN_OR_LEASE_OPTIONS = {
    '0': 'Lease',
    '1': 'Own'
  }.freeze

  LABEL_OPTIONS = {
    age: 'Age',
    anychildage: 'Age of children',
    gender: 'Gender',
    geocountry: 'Countries',
    geousregion: 'Regions',
    georegion: 'States/Provinces',
    rentorown: 'Rent or Own',
    ethnicity: 'Ethnicity',
    educationlevel: 'Education',
    employmentstatus: 'Employment',
    householdincome: 'Income',
    jobposition: 'Job Title',
    onlinepaymentmethod: 'Online payment method',
    ownlease: 'Own or lease your car',
    newoldvehicle: 'New or old vehicle',
    autopurchaseprospect: 'Plan on buying car in next 12 months',
    hightechdevices: 'What high tech devices do you use',
    employertype: 'Employer type',
    yearsinindustry: 'Years in the industry of employement',
    employmentdepartment: 'Employment department',
    smartphoneuse: 'How many hours per day do you use your smartphone',
    internetpersonaluse: 'Internet personal use',
    groceryshoppingduty: 'Grocery Shopping Duty',
    children: 'Children',
    industry: 'Industry',
    purchaseauth: 'Purchase Auth',
    financialdecisionmaker: 'Financial Decision Maker',
    investableassets: 'Investable Assets',
    insurancetype: 'Insurance Type',
    loantype: 'Loan Type',
    financialproduct: 'Financial Product',
    internetbusinessuse: 'Internet Business Use',
    onlineshopping: 'Online Shopping',
    onlinepurchase: 'Online Purchase',
    socialnetworks: 'Social Networks',
    socialnetworkuse: 'Social Network Use',
    favoritepublications: 'Favorite Publications',
    storetype: 'Store Type',
    purchaseditems: 'Purchased Items',
    grocerypurchases: 'Grocery Purchases',
    purchasetype: 'Purchase Type',
    restaurantvisits: 'How often do you go to restaurants',
    fastfoodvisits: 'How often do you go to fast-food restaurants',
    cookingfrequency: 'How often do you cook meals at home',
    alcoholconsumption: 'Do you drink alcoholic beverages',
    alcoholconsumptiontypes: 'Which of the following beverages have you consumed in the last 6 months',
    weeklyalcoholconsumption: 'How many alcoholic beverages do you consume per week on average',
    health: 'Which health areas affect you, a member of your household or someone you provide care for',
    personalhealth: 'Please indicate if you are currently suffering from, or have ever suffered from any of the following health issues',
    yearlytravelfrequency: 'How many times have you traveled in the last year for leisure or business purposes',
    travelsites: 'Which types of websites have you used to book your LEISURE travels in the past year',
    employeecount: 'Employee Count',
    vehicleownorlease: 'Vehicle Own or Lease',
    geopostalcode: 'Postal codes in the country\'s format (5 digit for US, 4 digit for Australia, and 6 digit for Canada)',
    geodmaregioncode: 'DMA (Designated Market Area) code'
  }.freeze
end
# rubocop:enable Metrics/ModuleLength
