# frozen_string_literal: true

# rubocop:disable Metrics/ClassLength
class AddFollowUpQuestions < ActiveRecord::Migration[5.2]
  def up
    expert_panel = Panel.find_by(slug: 'expert-panel')
    professional_category = expert_panel.demo_questions_categories.find_by(slug: 'professional')
    question_to_follow_up = professional_category.demo_questions.find_by(body: 'Which best describes the industry in which you work?')

    follow_up_question = professional_category.demo_questions.create(
      input_type: 'multiple',
      sort_order: 0,
      label: 'profession',
      body: 'Which of the following best describes your current profession? If you function in more than one role, please select all that apply.',
      parent_question: question_to_follow_up
    )

    DEMO_OPTIONS.each_with_index do |demo_option_array, index|
      follow_up_question.demo_options.create(
        label: demo_option_array.last,
        subject: demo_option_array.first,
        sort_order: index
      )
    end
  end

  def down
    demo_question = DemoQuestion.find_by(label: 'profession')
    demo_question.demo_options.delete_all
    demo_question.destroy
  end

  # rubocop:disable Style/WordArray
  DEMO_OPTIONS = [
    ['Banking/Financial', 'Branch Manager'],
    ['Banking/Financial', 'Financial Planning Director'],
    ['Banking/Financial', 'Auto Remarketing Manager'],
    ['Banking/Financial', 'Card Operations Manager'],
    ['Banking/Financial', 'Senior Business Development Manager'],
    ['Banking/Financial', 'Commercial Lending Director Senior'],
    ['Banking/Financial', 'Associate Branch Manager'],
    ['Banking/Financial', 'Auto Remarketing Specialist'],
    ['Banking/Financial', 'Compliance Research Manager'],
    ['Banking/Financial', 'Business Development Specialist'],
    ['Banking/Financial', 'Branch Coordinator'],
    ['Banking/Financial', 'ATM Specialist'],
    ['Banking/Financial', 'Card Operations Specialist'],
    ['Banking/Financial', 'Business Development Executive'],
    ['Banking/Financial', 'Commercial Loan Manager'],
    ['Banking/Financial', 'Commercial Credit Analyst'],
    ['Banking/Financial', 'Senior Business Development Executive'],
    ['Banking/Financial', 'Consumer Loan Manager'],
    ['Banking/Financial', 'Financial Planning Manager'],
    ['Banking/Financial', 'Customer Wealth Manager'],
    ['Banking/Financial', 'Credit Card Manager'],
    ['Banking/Financial', 'Human Resource Manager'],
    ['Banking/Financial', 'Cash Management Officer'],
    ['Banking/Financial', 'Taxation Executive'],
    ['Banking/Financial', 'Loan Executive'],
    ['Banking/Financial', 'Cheque Processing Officer'],
    ['Banking/Financial', 'Assistant BDE (Business Development Executive)'],
    ['Banking/Financial', 'Consumer Loan Executive'],
    ['Banking/Financial', 'Compliance Officer'],
    ['Banking/Financial', 'Credit Card Fraud Investigator'],
    ['Banking/Financial', 'Financial Services Representative'],
    ['Banking/Financial', 'Credit Card Fraud Analyst'],
    ['Banking/Financial', 'Foreign exchange Trader'],
    ['Banking/Financial', 'ATM Coordinator'],
    ['Banking/Financial', 'Investment Services Executive'],
    ['Banking/Financial', 'Foreclosure Specialist'],
    ['Banking/Financial', 'Clerk'],
    ['Banking/Financial', 'Security Associate'],
    ['Banking/Financial', 'Bank Teller'],
    ['Banking/Financial', 'Customer Support Associate'],
    ['Banking/Financial', 'Account Opening Executive'],
    ['Banking/Financial', 'Financial director'],
    ['Banking/Financial', 'Charted accountant'],
    ['Banking/Financial', 'Financial manager '],
    ['Banking/Financial', 'Financial accountant'],
    ['Banking/Financial', 'Other finance/banking role'],
    ['Beauty', 'Nail Care Artist'],
    ['Beauty', 'Dermatologist'],
    ['Beauty', 'Barber'],
    ['Beauty', 'Cosmetic Retailer'],
    ['Beauty', 'Tattoo Artist'],
    ['Beauty', 'Tattoo Remover'],
    ['Beauty', 'Electrolysis Hair Remover'],
    ['Beauty', 'Cosmetic/Plastic Surgeon'],
    ['Beauty', 'Soap Maker'],
    ['Beauty', 'Producer of hair products'],
    ['Beauty', 'Mobile Masseuse'],
    ['Beauty', 'Artificial Tanner'],
    ['Beauty', 'Sauna Bath Operator'],
    ['Beauty', 'Stretch Mark Remover'],
    ['Beauty', 'Herbal Soap Maker'],
    ['Beauty', 'Beauty Care Blogger'],
    ['Beauty', 'Cosmetologist'],
    ['Beauty', 'Make-Up Artist'],
    ['Beauty', 'Beauty Care Magazine Writer'],
    ['Beauty', 'Skin Care Consultant'],
    ['Beauty', 'Image Consultant/Stylist'],
    ['Beauty', 'Body Piercer'],
    ['Beauty', 'Wig Retailer'],
    ['Beauty', 'Beauty Exhibition Planner'],
    ['Beauty', 'Aroma Therapist'],
    ['Beauty', 'Teeth Whitening Specialist'],
    ['Beauty', 'Esthetician'],
    ['Beauty', 'Cosmetic Research Scientist'],
    ['Beauty', 'Cosmetic Wig Maker'],
    ['Beauty', 'Cosmetology Instructor/Lecturer'],
    ['Beauty', 'Mortuary Beautician'],
    ['Beauty', 'Mobile Manicurist'],
    ['Beauty', 'Salon Manager'],
    ['Beauty', 'Eyelash Technician'],
    ['Beauty', 'Beauty Counter Staff'],
    ['Beauty', 'Bridal Make-Up Specialist'],
    ['Beauty', 'Beauty Care Magazine Editor'],
    ['Beauty', 'Beauty Care Public Relations Specialist'],
    ['Beauty', 'Beauty School Owner'],
    ['Beauty', 'Dermal Therapist'],
    ['Beauty', 'Beauty Therapist'],
    ['Beauty', 'Hair Stylist'],
    ['Beauty', 'Other beauty role'],
    ['Contractor/Construction', 'Carpentry/Woodworker/Cabinet Maker'],
    ['Contractor/Construction', 'Drywall/Plaster'],
    ['Contractor/Construction', 'Electrician'],
    ['Contractor/Construction', 'Fencing/Decking'],
    ['Contractor/Construction', 'Flooring'],
    ['Contractor/Construction', 'Framer'],
    ['Contractor/Construction', 'General Contractor'],
    ['Contractor/Construction', 'Handyman/Property Maintenance'],
    ['Contractor/Construction', 'Home builder'],
    ['Contractor/Construction', 'Home or Property Restorer'],
    ['Contractor/Construction', 'HVAC'],
    ['Contractor/Construction', 'Insulation'],
    ['Contractor/Construction', 'Landscaper'],
    ['Contractor/Construction', 'Masonry'],
    ['Contractor/Construction', 'Painter'],
    ['Contractor/Construction', 'Plumber'],
    ['Contractor/Construction', 'Remodeler'],
    ['Contractor/Construction', 'Roofer'],
    ['Contractor/Construction', 'Siding/Windows/Doors'],
    ['Contractor/Construction', 'Other construction profession'],
    ['Education', 'Preschool teacher'],
    ['Education', 'Preschool administrator or staff'],
    ['Education', 'Elementary school teacher'],
    ['Education', 'Elementary school administrator or staff'],
    ['Education', 'Middle school teacher'],
    ['Education', 'Middle school administrator or staff'],
    ['Education', 'High school teacher'],
    ['Education', 'High school administrator or staff'],
    ['Education', 'University/college professor'],
    ['Education', 'University/college administrator or staff'],
    ['Education', 'Other education profession'],
    ['Food/Beverage/Restaurant', 'Baker'],
    ['Food/Beverage/Restaurant', 'Banquet manager'],
    ['Food/Beverage/Restaurant', 'Bartender'],
    ['Food/Beverage/Restaurant', 'Beverage manager'],
    ['Food/Beverage/Restaurant', 'Broiler cook'],
    ['Food/Beverage/Restaurant', 'Bus person'],
    ['Food/Beverage/Restaurant', 'Catering manager'],
    ['Food/Beverage/Restaurant', 'Counter server'],
    ['Food/Beverage/Restaurant', 'Dining room manager'],
    ['Food/Beverage/Restaurant', 'Executive chef'],
    ['Food/Beverage/Restaurant', 'Expediter'],
    ['Food/Beverage/Restaurant', 'Food and beverage director'],
    ['Food/Beverage/Restaurant', 'Fry/sauté cook'],
    ['Food/Beverage/Restaurant', 'General manager '],
    ['Food/Beverage/Restaurant', 'Human resources manager'],
    ['Food/Beverage/Restaurant', 'Kitchen manager'],
    ['Food/Beverage/Restaurant', 'Maître '],
    ['Food/Beverage/Restaurant', 'Pantry cooks'],
    ['Food/Beverage/Restaurant', 'Pastry chef'],
    ['Food/Beverage/Restaurant', 'President/CEO'],
    ['Food/Beverage/Restaurant', 'Public relations manager'],
    ['Food/Beverage/Restaurant', 'Server'],
    ['Food/Beverage/Restaurant', 'Soup and sauce cook'],
    ['Food/Beverage/Restaurant', 'Sous chef'],
    ['Food/Beverage/Restaurant', 'Wine steward'],
    ['Healthcare', 'Administrator'],
    ['Healthcare', 'Chiropractor'],
    ['Healthcare', 'Dental Hygienist or Assistant'],
    ['Healthcare', 'Dentist'],
    ['Healthcare', 'Emergency Medical Technician (EMT)'],
    ['Healthcare', 'Home health aide'],
    ['Healthcare', 'Medical assistant'],
    ['Healthcare', 'Nurse'],
    ['Healthcare', 'Nursing assistant'],
    ['Healthcare', 'Optometrist'],
    ['Healthcare', 'Pharmacist'],
    ['Healthcare', 'Phlebotomist'],
    ['Healthcare', 'Physical or Occupational Therapist'],
    ['Healthcare', 'Physician/Doctor'],
    ['Healthcare', 'Surgeon'],
    ['Healthcare', 'Technician (laboratory, radiology, etc.)'],
    ['Healthcare', 'Therapist or mental health counselor'],
    ['Healthcare', 'Veterinarian'],
    ['Healthcare', 'Other healthcare profession'],
    ['Human Resources', 'Benefits and Compensation'],
    ['Human Resources', 'Recruitment/Talent Acquisition'],
    ['Human Resources', 'Onboarding and Training'],
    ['Human Resources', 'Employer-Employee relations'],
    ['Human Resources', 'Learning and Career Development'],
    ['Human Resources', 'Human Resources Generalist'],
    ['Human Resources', 'Strategic Leadership'],
    ['Human Resources', 'Other Human Resources role'],
    ['Information Technology (IT)', 'Application Architecture and Integration'],
    ['Information Technology (IT)', 'Application Development'],
    ['Information Technology (IT)', 'Application Quality'],
    ['Information Technology (IT)', 'Audit, Compliance, Privacy'],
    ['Information Technology (IT)', 'Business Analytics'],
    ['Information Technology (IT)', 'Business Applications'],
    ['Information Technology (IT)', 'Cloud Architecture'],
    ['Information Technology (IT)', 'Customer Relationship Management (CRM)'],
    ['Information Technology (IT)', 'Data and Business Intelligence'],
    ['Information Technology (IT)', 'Data Architecture'],
    ['Information Technology (IT)', 'Data Center Architecture'],
    ['Information Technology (IT)', 'Enterprise Resource Planning (ERP)'],
    ['Information Technology (IT)', 'Enterprise/IT Risk Management/Digital Risk'],
    ['Information Technology (IT)', 'Information Security Management or Architecture'],
    ['Information Technology (IT)', 'IT Procurement Manager'],
    ['Information Technology (IT)', 'IT Service and Support Management'],
    ['Information Technology (IT)', 'IT Services Sourcing Manager'],
    ['Information Technology (IT)', 'IT Vendor Manager'],
    ['Information Technology (IT)', 'Mobile and Endpoint Computing Management'],
    ['Information Technology (IT)', 'Mobile Applications'],
    ['Information Technology (IT)', 'Program/Portfolio Management'],
    ['Information Technology (IT)', 'Server/Storage Architecture'],
    ['Information Technology (IT)', 'Software Asset Manager'],
    ['Information Technology (IT)', 'Telecom and Network Infrastructure'],
    ['Information Technology (IT)', 'Web Developer'],
    ['Information Technology (IT)', 'Other IT role/function'],
    ['Hospitality/Tourism', 'Casino Host'],
    ['Hospitality/Tourism', 'Cruise Ship Attendant'],
    ['Hospitality/Tourism', 'Front Desk Associate'],
    ['Hospitality/Tourism', 'Front Desk Supervisor'],
    ['Hospitality/Tourism', 'Front Office Attendant'],
    ['Hospitality/Tourism', 'Front-of-House Manager'],
    ['Hospitality/Tourism', 'Gaming Dealer'],
    ['Hospitality/Tourism', 'Guest Relations Manager'],
    ['Hospitality/Tourism', 'Guest Services Associate'],
    ['Hospitality/Tourism', 'Guest Services Supervisor'],
    ['Hospitality/Tourism', 'Hotel Clerk'],
    ['Hospitality/Tourism', 'Hotel Receptionist'],
    ['Hospitality/Tourism', 'Reservationist'],
    ['Hospitality/Tourism', 'Reservations Agent'],
    ['Hospitality/Tourism', 'Events Manager'],
    ['Hospitality/Tourism', 'Executive Conference Manager'],
    ['Hospitality/Tourism', 'Executive Meeting Manager'],
    ['Hospitality/Tourism', 'Meeting and Convention Planner'],
    ['Hospitality/Tourism', 'Meeting Coordinator'],
    ['Hospitality/Tourism', 'Meeting Manager'],
    ['Hospitality/Tourism', 'Meeting Planner'],
    ['Hospitality/Tourism', 'Meeting Specialist'],
    ['Hospitality/Tourism', 'Special Events Manager'],
    ['Hospitality/Tourism', 'Wedding Coordinator'],
    ['Hospitality/Tourism', 'Cafe Manager'],
    ['Hospitality/Tourism', 'Catering Manager'],
    ['Hospitality/Tourism', 'Food and Beverage Manager'],
    ['Hospitality/Tourism', 'Kitchen Manager'],
    ['Hospitality/Tourism', 'Pastry Chef'],
    ['Hospitality/Tourism', 'Restaurant Manager'],
    ['Hospitality/Tourism', 'Sous Chef'],
    ['Hospitality/Tourism', 'Back Office Assistant'],
    ['Hospitality/Tourism', 'Catering Sales Manager'],
    ['Hospitality/Tourism', 'Director of Hotel Sales'],
    ['Hospitality/Tourism', 'Director of Marketing and Sales'],
    ['Hospitality/Tourism', 'Group Sales Manager'],
    ['Hospitality/Tourism', 'Guest Room Sales Manager'],
    ['Hospitality/Tourism', 'Hotel Manager'],
    ['Hospitality/Tourism', 'Lodging Manager'],
    ['Hospitality/Tourism', 'Sales and Marketing Manager'],
    ['Hospitality/Tourism', 'Shift Leader'],
    ['Hospitality/Tourism', 'Shift Manager'],
    ['Hospitality/Tourism', 'Spa Manager'],
    ['Hospitality/Tourism', 'Wedding Sales Manager'],
    ['Hospitality/Tourism', 'Director of Housekeeping'],
    ['Hospitality/Tourism', 'Director of Maintenance'],
    ['Hospitality/Tourism', 'Director of Operations'],
    ['Hospitality/Tourism', 'Executive Housekeeper'],
    ['Hospitality/Tourism', 'Housekeeper'],
    ['Hospitality/Tourism', 'Housekeeping Aide'],
    ['Hospitality/Tourism', 'Housekeeping Supervisor'],
    ['Hospitality/Tourism', 'Maintenance Supervisor'],
    ['Hospitality/Tourism', 'Maintenance Worker'],
    ['Hospitality/Tourism', 'Baggage Porter'],
    ['Hospitality/Tourism', 'Bell Attendant'],
    ['Hospitality/Tourism', 'Bellhop'],
    ['Hospitality/Tourism', 'Bellman'],
    ['Hospitality/Tourism', 'Driver'],
    ['Hospitality/Tourism', 'Parking Lot Attendant'],
    ['Hospitality/Tourism', 'Valet'],
    ['Hospitality/Tourism', 'Valet Attendant'],
    ['Hospitality/Tourism', 'Valet Parking Attendant'],
    ['Hospitality/Tourism', 'Back Waiter'],
    ['Hospitality/Tourism', 'Banquet Server'],
    ['Hospitality/Tourism', 'Barback'],
    ['Hospitality/Tourism', 'Barista'],
    ['Hospitality/Tourism', 'Bartender'],
    ['Hospitality/Tourism', 'Busser'],
    ['Hospitality/Tourism', 'Cafe Manager'],
    ['Hospitality/Tourism', 'Catering Assistant'],
    ['Hospitality/Tourism', 'Food Runner'],
    ['Hospitality/Tourism', 'Food Server'],
    ['Hospitality/Tourism', 'Head Waiter'],
    ['Hospitality/Tourism', 'Sommelier'],
    ['Hospitality/Tourism', 'Other hospitality role'],
    ['Retail/Wholesale trade', 'Automotive Parts Counter Person'],
    ['Retail/Wholesale trade', 'Automotive Parts Specialist'],
    ['Retail/Wholesale trade', 'Cashier'],
    ['Retail/Wholesale trade', 'Customer Service Assistant'],
    ['Retail/Wholesale trade', 'Display Assistant'],
    ['Retail/Wholesale trade', 'Inventory Associate'],
    ['Retail/Wholesale trade', 'Inventory Taker'],
    ['Retail/Wholesale trade', 'Order Entry / Processor'],
    ['Retail/Wholesale trade', 'Paint Specialist'],
    ['Retail/Wholesale trade', 'Product Demonstrator'],
    ['Retail/Wholesale trade', 'Retail Customer Service Associate'],
    ['Retail/Wholesale trade', 'Retail Personal Banker'],
    ['Retail/Wholesale trade', 'Retail Sales Associate: Retail Sales Worker, Salesclerk, Retail Clerks, Salespeople'],
    ['Retail/Wholesale trade', 'Retail Sales Associate / Photographer'],
    ['Retail/Wholesale trade', 'Retail Sales Consultant'],
    ['Retail/Wholesale trade', 'Retail Sales Representative'],
    ['Retail/Wholesale trade', 'Retail Security Officer'],
    ['Retail/Wholesale trade', 'Retail Trainee'],
    ['Retail/Wholesale trade', 'Stock Clerk'],
    ['Retail/Wholesale trade', 'Stocker / Placer'],
    ['Retail/Wholesale trade', 'Warehouse Associate – Material Handler'],
    ['Retail/Wholesale trade', 'Wine Sales, Cashiers, and Stock Associates'],
    ['Retail/Wholesale trade', 'Customer Service Representative'],
    ['Retail/Wholesale trade', 'Department Manager'],
    ['Retail/Wholesale trade', 'Floor Area Manager'],
    ['Retail/Wholesale trade', 'Floor Leader'],
    ['Retail/Wholesale trade', 'Floor Manager'],
    ['Retail/Wholesale trade', 'Promotions Coordinator'],
    ['Retail/Wholesale trade', 'Retail Administration Analyst'],
    ['Retail/Wholesale trade', 'Retail Management Trainee'],
    ['Retail/Wholesale trade', 'Retail Marketing Specialist'],
    ['Retail/Wholesale trade', 'Retail Team Leader'],
    ['Retail/Wholesale trade', 'Service Supervisor'],
    ['Retail/Wholesale trade', 'Supervisor'],
    ['Retail/Wholesale trade', 'Team Leader'],
    ['Retail/Wholesale trade', 'Area Manager'],
    ['Retail/Wholesale trade', 'Assistant Merchandise Manager'],
    ['Retail/Wholesale trade', 'Assistant Store Manager'],
    ['Retail/Wholesale trade', 'Associate Product Manager'],
    ['Retail/Wholesale trade', 'Automotive Sales Manager'],
    ['Retail/Wholesale trade', 'Customer Service Manager'],
    ['Retail/Wholesale trade', 'District Sales Manager'],
    ['Retail/Wholesale trade', 'Divisional Manager'],
    ['Retail/Wholesale trade', 'General Manager'],
    ['Retail/Wholesale trade', 'Global Logistics Supervisor'],
    ['Retail/Wholesale trade', 'In-Store Assistant Branch Manager'],
    ['Retail/Wholesale trade', 'Manager of Retail Strategy Communications and Processes'],
    ['Retail/Wholesale trade', 'Meat Manager'],
    ['Retail/Wholesale trade', 'Regional Manager'],
    ['Retail/Wholesale trade', 'Retail Associate Store Manager'],
    ['Retail/Wholesale trade', 'Retail Food Service Manager'],
    ['Retail/Wholesale trade', 'Sales Manager'],
    ['Retail/Wholesale trade', 'Store Manager'],
    ['Retail/Wholesale trade', 'Warehouse Manager'],
    ['Retail/Wholesale trade', 'Assistant Buyer'],
    ['Retail/Wholesale trade', 'Associate Merchandise Buyer'],
    ['Retail/Wholesale trade', 'Buyer'],
    ['Retail/Wholesale trade', 'Delivery / Bulk Merchandiser'],
    ['Retail/Wholesale trade', 'Delivery Merchandiser Trainee'],
    ['Retail/Wholesale trade', 'Director of Merchandise Planning and Allocation'],
    ['Retail/Wholesale trade', 'Display Manager'],
    ['Retail/Wholesale trade', 'Display Merchandiser'],
    ['Retail/Wholesale trade', 'Executive Merchandise Trainee'],
    ['Retail/Wholesale trade', 'Inventory Manager'],
    ['Retail/Wholesale trade', 'Loss Prevention Specialist'],
    ['Retail/Wholesale trade', 'Merchandise Analyst'],
    ['Retail/Wholesale trade', 'Merchandise Buyer'],
    ['Retail/Wholesale trade', 'Merchandise Manager'],
    ['Retail/Wholesale trade', 'Merchandise Planner'],
    ['Retail/Wholesale trade', 'Merchandise Supervisor'],
    ['Retail/Wholesale trade', 'Procurement Specialist'],
    ['Retail/Wholesale trade', 'Visual Merchandiser'],
    ['Retail/Wholesale trade', 'Other retail role']
  ].freeze
  # rubocop:enable Style/WordArray
end
# rubocop:enable Metrics/ClassLength
